version: '3.8'

services:
  db:
    image: postgres:15
    container_name: aidart_db
    environment:
      POSTGRES_DB: aidart_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    container_name: aidart_backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/aidart_db
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  frontend:
    build: ./frontend
    container_name: aidart_frontend
    ports:
      - "4200:4200"
    stdin_open: true
    tty: true